config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :pictures

  get '/' => 'ideas#index'
  get 'search' => 'search#search'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture, dependent: :destroy
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_many :idea_images
  belongs_to :user
  has_many :pictures, as: :holder, dependent: :destroy
end

app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
end

app/models/idea_rate.rb
class IdeaRate < ActiveRecord::Base
end

app/models/idea_user.rb
class IdeaUser < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  # photoをattachファイルとする。stylesで画像サイズを定義できる
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_rate.rb
class UserRate < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.limit 4
    @tags = Tag.limit 10
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.fetch(:idea, {})
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
    @pictures = Picture.all
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title,:description, :required_user, :photo)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @ideas = []
    if params[:query].present?
      @ideas = Idea.where("title LIKE ?", "%"+params[:query]+"%").order("updated_at DESC").limit(5)
    end
    render template:"ideas/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>

  <div class="left-box">
    <img src="assets/top/background_pro.png">
  </div>
  
  <div class="right-box">
    <div class="boxes-title">
      <%= image_tag  "top/ic_rank.png" ,{class:"ic_new"}%>
      ランキング
    </div>
    <div class="">
      <% @ideas.each do |idea| %>
          <div class="single-box flex-item">
            <%= link_to(image_tag(idea.idea_images.first.url, class: "box_image"), idea)%>
            <p class="idea_title">
              <%= link_to idea.title, idea %>
            </p>
            <p class="idea_username">
              <%= link_to idea.user.username || "不明" , idea%>
            </p>
          </div>
      <% end %>
    </div>

  </div>

  <div class="maincontent">
    <div class="boxes">
      <div class="boxes-title">
        <%= image_tag  "top/ic_new.png" ,{class:"ic_new"}%>
        コメント待ちアイディア
      </div>
      <div class="flex-center">
        <% @ideas.each do |idea| %>
            <div class="single-box flex-item">
              <%= link_to(image_tag(idea.idea_images.first.url, class: "box_image"), idea)%>
              <p class="idea_title">
                <%= link_to idea.title, idea %>
              </p>
              <p class="idea_username">
                <%= link_to idea.user.username || "不明" , idea%>
              </p>
            </div>
        <% end %>
      </div>
      <div class="more">
        もっと見る
      </div>
    </div>

    <div class="boxes">
      <div class="boxes-title">
        <%= image_tag  "top/ic_reload.png" ,{class:"ic_new"}%>
        更新されたのアイディア
      </div>
      <div class="flex-center">
        <% @ideas.each do |idea| %>
            <div class="single-box flex-item">
              <%= link_to(image_tag(idea.idea_images.first.url, class: "box_image"), idea)%>
              <p class="idea_title">
                <%= link_to idea.title, idea %>
              </p>
              <p class="idea_username">
                <%= link_to idea.user.username || "不明" , idea%>
              </p>
            </div>
        <% end %>
      </div>
      <div class="more">
        もっと見る
      </div>
    </div>

    <div class="boxes">
      <div class="boxes-title">
        <%= image_tag  "top/ic_heart.png" ,{class:"ic_new"}%>
        あなたのアイディア
      </div>
      <div class="flex-center">
        <% @ideas.each do |idea| %>
            <div class="single-box flex-item">
              <%= link_to(image_tag(idea.idea_images.first.url, class: "box_image"), idea)%>
              <p class="idea_title">
                <%= link_to idea.title, idea %>
              </p>
              <p class="idea_username">
                <%= link_to idea.user.username || "不明" , idea%>
              </p>
            </div>
        <% end %>
      </div>
      <div class="more">
        もっと見る
      </div>
    </div>

  </div>
  </tbody>
</table>

<br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamKeidense</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <style type="text/css">
  .logo {
    display: block;
  }
  .copy {
    display: block;
  }
  .logout {
    float:right;
  }
  .container {
    margin:0;
  }
  .navbar {
    margin-bottom:0px;
  }
  </style>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <%= image_tag '/assets/logo.png', :class => "logo" %>
      <%= image_tag '/assets/copy.png', :class => "copy" %>
    </div>
    <%= image_tag '/assets/btn_logout.png', :class => "logout" %>
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
      </a>
    </div>
  </div>
  </nav>
<form id="search" action="/search/" method="get">
  <input type="text" name="query">
  <input type="submit" value="検索">
</form>



<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"タイトル" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :"説明" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :"必要としている人物" %><br>
    <%= f.text_field :required_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>投稿画面</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
<div class="col-md-10">
  <div class="main-box">
    <div class="idea-image">
     <%= image_tag @picture.photo.url(:medium) %>
   </div>
    <p>
      <%= label_tag 'タイトル' %>
      <%= @picture.title %>
    </p>
    <p>
      <%= label_tag 'アピール文' %>
      <%= @picture.description %>
    </p>
    <p>
      <%= label_tag '求めている人物' %>
      <%= @picture.required_user %>
    </p>
  </div>
</div>
<% if false %>
<%= link_to 'Edit', edit_picture_path(@picture) %>
<%= link_to 'Back', pictures_path %>
<% end %>
<div class="col-md-2">
   aaaa
</div>
</div>
</div>